name: Draft PDF
on:
  push:
    paths:
      - paper.md
      - paper.bib
      - 'User%20guide%20images/over1.png'
      - 'User%20guide%20images/over2.png'
      
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf
